AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Client:
    Type: String
    Default: geth
  Network:
    Type: String
    Default: mainnet
  Build:
    Type: String
  InstanceSize:
    Type: String
    Default: xlarge

  HotVolumeSize:
    Type: Number
    Default: 400
  HotVolumeThroughput:
    Type: Number
    Default: 125
  HotVolumeIops:
    Type: Number
    Default: 3000

  ColdVolumeSize:
    Type: Number
    Default: 450
  ColdVolumeThroughput:
    Type: Number
    Default: 125
  ColdVolumeIops:
    Type: Number
    Default: 3000

  JsonWebToken:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /cfn/dap/prysm/mainnet/jwt
  EnableBackup:
    Type: String
    Default: false
  NetRestrict:
    Type: String
    Default: false

Resources:
  Stack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Client: !Ref Client
        Build: !Ref Build
        InstanceSize: !Ref InstanceSize

        HotVolumeSize: !Ref HotVolumeSize
        HotVolumeThroughput: !Ref HotVolumeThroughput
        HotVolumeIops: !Ref HotVolumeIops

        ColdVolumeSize: !Ref ColdVolumeSize
        ColdVolumeThroughput: !Ref ColdVolumeThroughput
        ColdVolumeIops: !Ref ColdVolumeIops

        JsonWebToken: !Ref JsonWebToken
        EnableBackup: !Ref EnableBackup
        NetRestrict: !Ref NetRestrict
        SecurityGroups: !Join 
          - ','
          - - !ImportValue dap-network-listener-sg
            - !ImportValue dap-network-discovery-sg
            - !ImportValue dap-network-http-sg
            - !ImportValue dap-network-ws-sg
      TemplateURL: !Sub https://dap-${AWS::Region}-client-${AWS::AccountId}.s3.${AWS::Region}.amazonaws.com/templates/client.yaml

