AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Client:
    Type: String
    Default: prysm
  Network:
    Type: String
    Default: mainnet
  Build:
    Type: String
  InstanceSize:
    Type: String
    Default: large
  HotVolumeSize:
    Type: Number
    Default: 150
  ColdVolumeSize:
    Type: Number
    Default: 0
  Endpoint:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /cfn/dap/network/geth/ip/eni
  JsonWebToken:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /cfn/dap/prysm/mainnet/jwt

Resources:
  Stack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Client: !Ref Client
        Build: !Ref Build
        InstanceSize: !Ref InstanceSize
        HotVolumeSize: !Ref HotVolumeSize
        ColdVolumeSize: !Ref ColdVolumeSize
        Endpoint: !Ref Endpoint
        JsonWebToken: !Ref JsonWebToken
        SecurityGroups: !Join 
          - ','
          - - !ImportValue dap-network-prysm-sg
      TemplateURL: !Sub https://dap-${AWS::Region}-client-${AWS::AccountId}.s3.${AWS::Region}.amazonaws.com/templates/client.yaml

