{
 "title": "Prysm",
 "time": { "from": "now-90m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node_job", "query": "prysm-nodes" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prysm-nodes\"}[15s])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (beacon_clock_time_slot - beacon_head_slot) / beacon_clock_time_slot * 100"
    },
    {}
   ]
  },
  {
   "title": "OoS Hours",
   "type": "stat",
   "description": "out-of-sync hours",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(beacon_clock_time_slot - beacon_head_slot) * 12 / 60 / 60"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prysm_version" }
   ]
  },
  {
   "title": "10m Logs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(log_entries_total{job=\"$node_job\", level=\"error\"}[10m]) * 100",
     "legendFormat": "Errors"
    },
    {
     "expr": "rate(log_entries_total{job=\"$node_job\", level=\"warning\"}[10m]) * 100",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "connected_libp2p_peers{job=\"prysm-nodes\"}",
     "legendFormat": "{{ agent }}"
    }
   ]
  },
  {
   "title": "Beacon Chain Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bcnode_disk_beaconchain_bytes_total{job=\"prysm-nodes\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prysm-nodes\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prysm-nodes\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bolt DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(bolt_tx_writes_total{job=\"prysm-nodes\"}[1m])",
     "legendFormat": "tx writes"
    },
    {
     "expr": "rate(bolt_db_read_tx_total{job=\"prysm-nodes\"}[1m])",
     "legendFormat": "tx reads"
    }
   ]
  },
  {
   "title": "Average Scores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "connected_libp2p_peers_average_scores{job=\"prysm-nodes\"}",
     "legendFormat": "{{ agent }}"
    }
   ]
  }
 ]
}