apiVersion: v1
kind: ServiceAccount
metadata:
  name: superset-dapp-installer
  namespace: superset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: superset-dapp-installer
  namespace: superset
rules:
  ${EXEC_RULES}
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: superset-dapp-installer
  namespace: superset
subjects:
- kind: ServiceAccount
  name: superset-dapp-installer
  namespace: superset
roleRef:
  kind: Role
  name: superset-dapp-installer
  apiGroup: rbac.authorization.k8s.io

