apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hive-site
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://{{ .Release.Name }}-postgresql/hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>{{ .Values.postgresql.postgresqlUsername }}</value>
      </property>
      <property>
        <name> javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.postgresql.postgresqlPassword }}</value>
      </property>
      <property>
        <name>hive.metastore.uris</name>
        <value>thrift://{{ .Release.Name }}-hive-metastore:9083</value>
      </property>
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>file:///tmp</value>
      </property>
    </configuration>

