apiVersion: batch/v1
kind: Job
metadata:
  name: metastore-image
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.depBuild }}
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: metastore-image
    spec:
      restartPolicy: Never
      containers:
      - name: metastore-image
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=/mnt"
        - "--destination={{ .Values.global.registry }}:metastore"
        - "--cache=true"
        resources:
          requests:
            cpu: 800m
            memory: 7Gi
        volumeMounts:
        - name: dockerfile
          mountPath: /mnt
      volumes:
      - name: dockerfile
        configMap:
          name: metastore-dockerfile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-dockerfile
  annotations:
    argocd.argoproj.io/hook: {{ .Values.global.depBuild }}
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  Dockerfile: |
    FROM openjdk:11-jre-slim

    ARG VERSION=2.3.9
    ARG TAR=apache-hive-$VERSION-bin.tar.gz
    ARG HIVE_URL=https://dlcdn.apache.org/hive/hive-$VERSION/$TAR
    ARG HADOOP={{ .Values.global.hadoopVersion }}
    ARG AWS={{ .Values.global.awsSdkVersion }}
    
    ENV HIVE_HOME=/opt/hive
    ENV PATH=$HIVE_HOME/bin:$PATH
    ENV HADOOP_HOME=/opt/hadoop-$HADOOP

    RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* && \
        curl -O $HIVE_URL && tar -xvf $TAR && rm $TAR && \
        mv apache-hive-$VERSION-bin $HIVE_HOME && \
        curl -O https://dlcdn.apache.org/hadoop/common/hadoop-$HADOOP/hadoop-$HADOOP.tar.gz && \
        tar -xvf hadoop-$HADOOP.tar.gz && rm hadoop-$HADOOP.tar.gz && mv hadoop-$HADOOP /opt && \
        apt-get autoremove -y curl

    ARG DEST=$HIVE_HOME/lib/
    ARG MVN=https://repo1.maven.org/maven2
    ADD $MVN/org/apache/hadoop/hadoop-aws/$HADOOP/hadoop-aws-$HADOOP.jar $DEST
    ADD $MVN/com/amazonaws/aws-java-sdk-bundle/$AWS/aws-java-sdk-bundle-$AWS.jar $DEST
    ADD https://jdbc.postgresql.org/download/postgresql-42.3.1.jar $DEST
    
    WORKDIR $HIVE_HOME

