apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-hive-metastore
spec:
  selector:
    matchLabels:
      app/instance: {{ .Release.Name }}
      app/name: hive-metastore
  serviceName: {{ .Release.Name }}-hive-metastore
  replicas: 1
  template:
    metadata:
      labels:
        app/instance: {{ .Release.Name }}
        app/name: hive-metastore
    spec:
      containers:
      - name: metastore
        image: {{ .Values.global.registry }}:metastore
        imagePullPolicy: Always
        resources:
          requests:
            memory: 230Mi
        {{ $command := "hive --service metastore" }}
        command:
        - /bin/sh
        - -c
        - "{{ $command }} || (schematool -initSchema -dbType postgres && {{ $command }})"
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
      volumes:
      - name: hive-config
        configMap:
          name: {{ .Release.Name }}-hive-site

