apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-aws-setup
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-aws-setup
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}-aws-setup
        image: amazon/aws-cli
        command: ["/bin/bash"]
        args: ["/mnt/aws-setup.sh"]
        volumeMounts:
        - name: script
          mountPath: /mnt
      volumes:
      - name: script
        configMap:
          name: {{ .Release.Name }}-aws-setup
          defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-aws-setup
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-99"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  aws-setup.sh: |

    repo_name={{ .Values.clusterName }}/airflow 
    aws ecr describe-repositories --repository-names $repo_name ||
        aws ecr create-repository --repository-name $repo_name

    bucket_name={{ trimPrefix "s3://" .Values.airflow.config.logging.remote_base_log_folder }}
    aws s3api head-bucket --bucket $bucket_name || aws s3 mb s3://$bucket_name

