apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: redash-install
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1hook"
        value: Skip
  - target:
      group: batch
      version: v1
      kind: Job
      name: redash-upgrade
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1hook"
        value: Skip

