# Replace helm Job not triggering due to post-install and post-upgrade hooks waiting for a healthy state in Argo CD.
# Template taken from https://github.com/apache/airflow/blob/main/chart/templates/jobs/migrate-database-job.yaml.
# Helm hook annotations have been replaced by argo Sync hook and references now point to airflow dependency.

{{- $nodeSelector := or .Values.airflow.migrateDatabaseJob.nodeSelector .Values.airflow.nodeSelector }}
{{- $affinity := or .Values.airflow.migrateDatabaseJob.affinity .Values.airflow.affinity }}
{{- $tolerations := or .Values.airflow.migrateDatabaseJob.tolerations .Values.airflow.tolerations }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-run-airflow-migrations-2
  labels:
    tier: airflow
    component: run-airflow-migrations-2
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.airflow.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        tier: airflow
        component: run-airflow-migrations-2
        release: {{ .Release.Name }}
      {{- if or .Values.airflow.airflowPodAnnotations .Values.airflow.migrateDatabaseJob.annotations }}
      annotations:
        {{- if .Values.airflow.airflowPodAnnotations }}
        {{- toYaml .Values.airflow.airflowPodAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.airflow.migrateDatabaseJob.annotations }}
        {{- toYaml .Values.airflow.migrateDatabaseJob.annotations | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      securityContext:
          runAsUser: {{ .Values.airflow.uid }}
      restartPolicy: OnFailure
      nodeSelector:
{{ toYaml $nodeSelector | indent 8 }}
      affinity:
{{ toYaml $affinity | indent 8 }}
      tolerations:
{{ toYaml $tolerations | indent 8 }}
      serviceAccountName: {{ include "call-nested" (list . "airflow" "migrateDatabaseJob.serviceAccountName") }}
      {{- if or .Values.airflow.registry.secretName .Values.airflow.registry.connection }}
      imagePullSecrets:
        - name: {{ template "registry_secret" . }}
      {{- end }}
      containers:
        - name: run-airflow-migrations-2
          image: {{ template "call-nested" (list . "airflow" "airflow_image") }}
          imagePullPolicy: {{ .Values.airflow.images.airflow.pullPolicy }}
          # Support running against 1.10.x and 2.x
          {{- if semverCompare ">=2.0.0" .Values.airflow.airflowVersion }}
          args: ["bash", "-c", "airflow db upgrade"]
          {{- else }}
          args: ["bash", "-c", "airflow upgradedb"]
          {{- end }}
          env:
          {{- include "call-nested" (list . "airflow" "standard_airflow_environment") | indent 10 }}
          volumeMounts:
            - name: config
              mountPath: {{ template "call-nested" (list . "airflow" "airflow_config_path") }}
              subPath: airflow.cfg
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "call-nested" (list . "airflow" "airflow_config") }}

