airflow:
  defaultAirflowTag: latest
  executor: KubernetesExecutor
  extraEnvFrom: |
    - configMapRef:
        name: env 
  migrateDatabaseJob:
    jobAnnotations:
      argocd.argoproj.io/hook: Skip
  dags:
    gitSync:
      subPath: airflow/dags
  images:
    airflow:
      pullPolicy: Always
  webserver:
    defaultUser:
      enabled: false
  postgresql:
    persistence:
      enabled: true
      existingClaim: postgresql-0
  config:
    webserver:
      expose_config: 'True'
    logging:
      remote_logging: 'True'

