airflow:
  defaultAirflowTag: latest
  executor: KubernetesExecutor
  extraEnvFrom: |
    - configMapRef:
        name: env 
  migrateDatabaseJob:
    jobAnnotations:
      argocd.argoproj.io/hook: Skip
  dags:
    gitSync:
      subPath: airflow/dags
  images:
    airflow:
      pullPolicy: Always
  webserver:
    resources:
      requests:
        memory: 1300Mi
    defaultUser:
      enabled: false
  postgresql:
    persistence:
      enabled: true
  config:
    webserver:
      expose_config: 'True'
    logging:
      remote_logging: 'True'
    core:
      store_dag_code: 'False'
      dagbag_import_timeout: 60.0

