apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-dapp-installer
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-dapp-installer
  namespace: spark
rules:
  ${EXEC_RULES}
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-dapp-installer
  namespace: spark
subjects:
- kind: ServiceAccount
  name: spark-dapp-installer
  namespace: spark
roleRef:
  kind: Role
  name: spark-dapp-installer
  apiGroup: rbac.authorization.k8s.io

