apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml

# uncomment patch and log into container for ad hoc maintenance
#patchesJson6902:
#  - target:
#      group: apps
#      version: v1
#      kind: StatefulSet
#      name: sparkubi-hive-metastore
#    patch: |-
#      - op: replace
#        path: /spec/template/spec/containers/0/command
#        value: 
#        - /bin/sh
#        - -c
#        - "sleep 3600"

