build:
  baseImage: sparkubi-dep-{{ .Values.sparkVersion }}
postgresql:
  postgresqlUsername: hive
  postgresqlPassword: hive
  postgresqlDatabase: hive
chartmuseum:
  env:
    open:
      DISABLE_API: false 
      ALLOW_OVERWRITE: true
      AWS_SDK_LOAD_CONFIG: true
      STORAGE: amazon
      STORAGE_AMAZON_PREFIX: spark
