{{ $profile := tpl ".Values.global.profiles.{{ .Values.global.profile }}" . }}
{{ $coldBuild := tpl (printf "{{ %s.coldBuild }}" $profile) . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-image
  annotations:
    argocd.argoproj.io/hook: {{ $coldBuild }}
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: kafka-image
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-image
        image: gcr.io/kaniko-project/executor:{{ .Values.global.kanikoVersion }}
        args:
        - "--context=/mnt"
        - "--destination={{ .Values.global.registry }}:kafka-{{ .Values.kafkaVersion }}"
        - "--cache=true"
        volumeMounts:
        - name: dockerfile
          mountPath: /mnt
      volumes:
      - name: dockerfile
        configMap:
          name: kafka-dockerfile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-dockerfile
  annotations:
    argocd.argoproj.io/hook: {{ $coldBuild }}
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  Dockerfile: |
    FROM openjdk:11-jre-slim

    ARG KAFKA_VERSION={{ .Values.kafkaVersion }}
    ARG KAFKA_RELEASE={{ tpl .Values.kafkaRelease . }}
    # recent version links downloads.apache.org or dlcdn.apache.org tend to break:
    # stable download from https://archive.apache.org/dist/kafka/VERSION/RELEASE.tgz
    ARG URL=https://archive.apache.org/dist/kafka/$KAFKA_VERSION/$KAFKA_RELEASE.tgz

    RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* && \
        mkdir /opt/dap && curl -O $URL && tar -xzf $KAFKA_RELEASE.tgz -C /opt/dap && \
        rm $KAFKA_RELEASE.tgz && apt-get autoremove -y curl
    
    WORKDIR /opt/dap/$KAFKA_RELEASE
    ENTRYPOINT ["bash", "-c"]

